/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package filestorageclient;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;

public class frmLogin extends javax.swing.JFrame {

    // Khai báo đối tượng quản lý kết nối Socket
    private final ClientSocketManager clientManager;

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(frmLogin.class.getName());

    /**
     * Creates new form frmLogin
     */
    public frmLogin() {
        // Khởi tạo ClientSocketManager và cố gắng kết nối ngay
        clientManager = new ClientSocketManager();
        if (!clientManager.connect()) {
            JOptionPane.showMessageDialog(this,
                    "Lỗi kết nối Server. Vui lòng kiểm tra Server có đang chạy không.",
                    "Lỗi Kết Nối", JOptionPane.ERROR_MESSAGE);
        }

        initComponents();

        this.setLocationRelativeTo(null); // Đặt cửa sổ giữa màn hình
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextField();
        txtPassword = new javax.swing.JPasswordField();
        btnLogin = new javax.swing.JButton();
        btnRegister = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Đăng nhập");

        jLabel1.setText("Username");

        jLabel2.setText("Password");

        txtUsername.setText("Username");

        txtPassword.setText("jPasswordField1");

        btnLogin.setText("Login");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });

        btnRegister.setText("Register");
        btnRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegisterActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnLogin)
                        .addGap(34, 34, 34)
                        .addComponent(btnRegister))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtUsername)
                            .addComponent(txtPassword, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE))))
                .addContainerGap(152, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLogin)
                    .addComponent(btnRegister))
                .addContainerGap(163, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        handleLogin(); // Gọi logic xử lý chính
    }//GEN-LAST:event_btnLoginActionPerformed

    private void btnRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisterActionPerformed
        handleRegisterButton(); // Gọi logic xử lý chính
    }//GEN-LAST:event_btnRegisterActionPerformed
    /**
     * Logic xử lý chức năng Đăng nhập. Thực hiện kiểm tra đầu vào và gọi phương
     * thức login() qua SwingWorker.
     */
    private void handleLogin() {
        String username = txtUsername.getText().trim();
        String password = new String(txtPassword.getPassword());

        if (username.isEmpty() || password.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập đầy đủ Tên đăng nhập và Mật khẩu.",
                    "Thiếu thông tin", JOptionPane.WARNING_MESSAGE);
            return;
        }

        // Tắt nút để tránh nhấn kép
        btnLogin.setEnabled(false);

        // Khởi tạo và chạy SwingWorker
        new javax.swing.SwingWorker<String, Void>() {
            @Override
            protected String doInBackground() throws Exception {
                // THAO TÁC BLOCKING CHẠY Ở LUỒNG NỀN
                return clientManager.login(username, password);
            }

            @Override
            protected void done() {
                try {
                    // KẾT QUẢ ĐƯỢC NHẬN VÀ CHẠY TRÊN EDT
                    String result = get(); // Lấy kết quả từ doInBackground()

                    if (result.startsWith("LOGIN_SUCCESS:")) {
                        String loggedInUsername = result.substring("LOGIN_SUCCESS:".length()).trim();
                        JOptionPane.showMessageDialog(frmLogin.this, "Đăng nhập thành công! Chào mừng " + loggedInUsername);

                        // Mở form chính
                        new frmMainClient(loggedInUsername, clientManager).setVisible(true);
                        frmLogin.this.dispose();

                    } else if ("LOGIN_FAIL".equals(result)) {
                        JOptionPane.showMessageDialog(frmLogin.this, "Tên đăng nhập hoặc mật khẩu không đúng.",
                                "Lỗi Đăng nhập", JOptionPane.ERROR_MESSAGE);
                        txtPassword.setText("");
                    } else {
                        JOptionPane.showMessageDialog(frmLogin.this, "Lỗi hệ thống: " + result,
                                "Lỗi", JOptionPane.ERROR_MESSAGE);
                        if ("ERROR_CONNECTION".equals(result) || "ERROR_IO".equals(result)) {
                            clientManager.connect();
                        }
                    }
                } catch (Exception ex) {
                    logger.log(java.util.logging.Level.SEVERE, "Lỗi SwingWorker khi Đăng nhập", ex);
                    JOptionPane.showMessageDialog(frmLogin.this, "Lỗi không xác định: " + ex.getMessage(),
                            "Lỗi", JOptionPane.ERROR_MESSAGE);
                } finally {
                    btnLogin.setEnabled(true); // Bật lại nút dù thành công hay thất bại
                }
            }
        }.execute(); // Chạy SwingWorker
    }

    /**
     * Logic xử lý chức năng Đăng ký. Mở form đăng ký và ẩn form đăng nhập hiện
     * tại.
     */
    private void handleRegisterButton() {
        // Cần đảm bảo rằng frmRegister có constructor nhận (JFrame, ClientSocketManager)
        frmRegister registerForm = new frmRegister(this, clientManager);

        // Ẩn form Login hiện tại để người dùng tập trung vào form Đăng ký
        this.setVisible(false);

        // Hiển thị form Đăng ký
        registerForm.setVisible(true);
    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // Cần đảm bảo chạy trên Event Dispatch Thread (luồng của Swing)
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new frmLogin().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogin;
    private javax.swing.JButton btnRegister;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}
