/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package filestorageclient;

import java.io.File;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.awt.event.ActionEvent;
import java.util.logging.Level;

public class frmMainClient extends javax.swing.JFrame {

    // Khai báo các biến Logic và UI (Đảm bảo tên khớp với Design View)
    private final ClientSocketManager clientManager;
    private final String username;

    private DefaultTableModel tableModel;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(frmMainClient.class.getName());

    /**
     * Khởi tạo form frmMainClient.
     *
     * @param username Tên người dùng hiện tại.
     * @param manager Đối tượng quản lý kết nối socket.
     */
    public frmMainClient(String username, ClientSocketManager manager) {
        this.username = username;
        this.clientManager = manager;

        initComponents();
        initializeTable(); // Khởi tạo JTable

        lblWelcome.setText("Xin chào, " + username + "!"); // Cập nhật lời chào
        this.setLocationRelativeTo(null);
        this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE); // Đóng ứng dụng khi đóng cửa sổ chính
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblWelcome = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        fileTable = new javax.swing.JTable();
        btnLogout = new javax.swing.JButton();
        btnUpload = new javax.swing.JButton();
        btnDownload = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnShare = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Quản lý File - File Storage Client");

        lblWelcome.setText("Xin chào, [Username]!");

        fileTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "File name", "Size", "Date modified", "Status", "Sharer"
            }
        ));
        jScrollPane1.setViewportView(fileTable);

        btnLogout.setText("Logout");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        btnUpload.setText("Upload");
        btnUpload.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUploadActionPerformed(evt);
            }
        });

        btnDownload.setText("Download");
        btnDownload.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDownloadActionPerformed(evt);
            }
        });

        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnShare.setText("Share");
        btnShare.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShareActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 654, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblWelcome)
                .addGap(39, 39, 39)
                .addComponent(btnLogout)
                .addGap(34, 34, 34))
            .addGroup(layout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addComponent(btnUpload)
                .addGap(18, 18, 18)
                .addComponent(btnDownload)
                .addGap(18, 18, 18)
                .addComponent(btnShare)
                .addGap(45, 45, 45)
                .addComponent(btnDelete)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblWelcome)
                    .addComponent(btnLogout))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 389, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnUpload)
                    .addComponent(btnDownload)
                    .addComponent(btnDelete)
                    .addComponent(btnShare))
                .addGap(45, 45, 45))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    /**
     * Khởi tạo cấu trúc bảng và tải danh sách file ban đầu
     */
    private void initializeTable() {
        // 1. Định nghĩa cấu trúc cột (Đảm bảo có đủ 5 cột)
        String[] columnNames = {"File ID", "File Name", "Size (bytes)", "Upload Date", "Status", "Sharer"}; // <--- CHẮC CHẮN MẢNG NÀY CÓ "Status"
        tableModel = new DefaultTableModel(columnNames, 0) {
            // Ngăn người dùng chỉnh sửa trực tiếp trên bảng
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        fileTable.setModel(tableModel);

        // 2. Ẩn cột "File ID" (Cột 0)
        fileTable.getColumnModel().getColumn(0).setPreferredWidth(0);
        fileTable.getColumnModel().getColumn(0).setMinWidth(0);
        fileTable.getColumnModel().getColumn(0).setMaxWidth(0);

        // 3. Thiết lập chiều rộng cho cột Status (Cột 4) (Tùy chọn)
        fileTable.getColumnModel().getColumn(4).setPreferredWidth(60);
        fileTable.getColumnModel().getColumn(4).setMaxWidth(80);

        fileTable.getColumnModel().getColumn(5).setPreferredWidth(100);
        fileTable.getColumnModel().getColumn(5).setMaxWidth(150);

        // 4. Tải dữ liệu ban đầu
        loadFileList();
    }

    // LOGIC XỬ LÝ CHỨC NĂNG
    /**
     * Tải danh sách file từ Server và cập nhật JTable
     */
    public void loadFileList() {
        tableModel.setRowCount(0); // Xóa dữ liệu cũ ngay trên EDT

        new SwingWorker<String, Void>() {
            @Override
            protected String doInBackground() throws Exception {
                // Thao tác mạng chạy ở luồng nền
                return clientManager.listFiles();
            }

            @Override
            protected void done() {
                try {
                    String response = get();

                    // 1. Kiểm tra tiền tố phản hồi của Server
                    if (response.startsWith("FILELIST_START:")) { // Dùng tiền tố đã thống nhất
                        String data = response.substring("FILELIST_START:".length());

                        if (data.isEmpty()) {
                            return;
                        }

                        // 2. Tách từng bản ghi file (phân tách bằng ";")
                        String[] files = data.split(";");

                        for (String fileInfo : files) {
                            if (fileInfo.trim().isEmpty()) {
                                continue;
                            }

                            // 3. Tách thông tin file (phân tách bằng "|") - PHẢI DÙNG "\\|"
                            String[] parts = fileInfo.split("\\|", -1);

                            // Server gửi 6 phần: ID|TênFile|KíchThước|NgàyUpload|Status|Sharer
                            if (parts.length == 6) {

                                // Format kích thước (parts[2])
                                long fileSize = Long.parseLong(parts[2]);
                                String formattedSize = formatSize(fileSize);

                                // Status (parts[4]
                                String sharerName = parts[5];
                                if (sharerName.isEmpty()) {
                                    // Nếu là file Owned, Sharer là trống, hiển thị là "-" hoặc để trống
                                    sharerName = "";
                                }

                                // Status (parts[4]) đã là chuỗi "Owned" hoặc "Shared"
                                Object[] rowData = new Object[]{
                                    parts[0], // File ID (Cột 0 - ẩn)
                                    parts[1], // File Name (Cột 1)
                                    formattedSize, // Size đã format (Cột 2)
                                    parts[3], // Upload Date (Cột 3)
                                    parts[4], // Status (Cột 4)
                                    sharerName // Sharer (Cột 5)
                                };
                                tableModel.addRow(rowData);
                            } else {
                                logger.warning("Dữ liệu file không hợp lệ (Số lượng cột sai): " + fileInfo);
                            }
                        }
                    } else if (response.equals("FILELIST_FAIL_SERVER_ERROR")) {
                        JOptionPane.showMessageDialog(frmMainClient.this, "Lỗi Server khi tải danh sách file.", "Lỗi", JOptionPane.ERROR_MESSAGE);
                    } else {
                        JOptionPane.showMessageDialog(frmMainClient.this, "Không thể tải danh sách file: " + response, "Lỗi", JOptionPane.ERROR_MESSAGE);
                    }
                } catch (Exception ex) {
                    logger.log(Level.SEVERE, "Lỗi khi tải danh sách file", ex);
                    JOptionPane.showMessageDialog(frmMainClient.this, "Lỗi kết nối khi tải danh sách file: " + ex.getMessage(), "Lỗi", JOptionPane.ERROR_MESSAGE);
                }
            }
        }.execute();
    }

    /**
     * Xử lý Đăng xuất
     */
    private void handleLogout() {
        int confirm = JOptionPane.showConfirmDialog(this, "Bạn có chắc chắn muốn đăng xuất?", "Xác nhận", JOptionPane.YES_NO_OPTION);

        if (confirm == JOptionPane.YES_OPTION) {
            new SwingWorker<Void, Void>() {
                @Override
                protected Void doInBackground() throws Exception {
                    clientManager.logout();
                    return null;
                }

                @Override
                protected void done() {
                    // Quay lại form Login trên EDT
                    try {
                        // Dùng Class.forName và Reflection để tránh lỗi nếu frmLogin chưa được tạo
                        Class<?> loginClass = Class.forName("filestorageclient.frmLogin");
                        JFrame loginForm = (JFrame) loginClass.getDeclaredConstructor().newInstance();
                        loginForm.setVisible(true);
                    } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | NoSuchMethodException | java.lang.reflect.InvocationTargetException e) {
                        logger.log(Level.WARNING, "Không tìm thấy hoặc không thể khởi tạo frmLogin. Đảm bảo lớp này tồn tại.", e);
                        JOptionPane.showMessageDialog(frmMainClient.this, "Đăng xuất thành công! Không tìm thấy form Login.", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
                    } finally {
                        frmMainClient.this.dispose();
                    }
                }
            }.execute();
        }
    }

    /**
     * Xử lý Tải file lên (Upload)
     */
    private void handleUpload() {
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setFileSelectionMode(JFileChooser.FILES_ONLY);
        int result = fileChooser.showOpenDialog(this);

        if (result == JFileChooser.APPROVE_OPTION) {
            File selectedFile = fileChooser.getSelectedFile();

            btnUpload.setEnabled(false); // Vô hiệu hóa nút trên EDT

            new SwingWorker<String, Void>() {
                @Override
                protected String doInBackground() throws Exception {
                    // Thao tác mạng nặng chạy ở luồng nền
                    return clientManager.uploadFile(selectedFile);
                }

                @Override
                protected void done() {
                    try {
                        String uploadResult = get();

                        if ("UPLOAD_SUCCESS".equals(uploadResult)) {
                            JOptionPane.showMessageDialog(frmMainClient.this, "Upload file '" + selectedFile.getName() + "' thành công!");
                            loadFileList(); // Cập nhật bảng
                        } else {
                            JOptionPane.showMessageDialog(frmMainClient.this, "Upload thất bại: " + uploadResult, "Lỗi", JOptionPane.ERROR_MESSAGE);
                        }
                    } catch (Exception ex) {
                        logger.log(Level.SEVERE, "Lỗi khi Upload file", ex);
                        JOptionPane.showMessageDialog(frmMainClient.this, "Lỗi hệ thống khi upload: " + ex.getMessage(), "Lỗi", JOptionPane.ERROR_MESSAGE);
                    } finally {
                        btnUpload.setEnabled(true); // Bật lại nút
                    }
                }
            }.execute();
        }
    }

    /**
     * Xử lý Tải file về (Download)
     */
    private void handleDownload() {
        int selectedRow = fileTable.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn một file để tải xuống.", "Cảnh báo", JOptionPane.WARNING_MESSAGE);
            return;
        }

        // Lấy thông tin file trên EDT
        String fileIdStr = (String) tableModel.getValueAt(selectedRow, 0);
        int fileId = Integer.parseInt(fileIdStr);
        String fileName = (String) tableModel.getValueAt(selectedRow, 1);

        // Mở cửa sổ chọn nơi lưu file
        JFileChooser fileChooser = new JFileChooser();
        // Gợi ý tên file mặc định
        fileChooser.setSelectedFile(new File(fileName));
        fileChooser.setDialogTitle("Chọn nơi lưu file: " + fileName);

        int userSelection = fileChooser.showSaveDialog(this);

        if (userSelection == JFileChooser.APPROVE_OPTION) {
            File fileToSave = fileChooser.getSelectedFile();

            btnDownload.setEnabled(false); // Vô hiệu hóa nút trên EDT để tránh click kép

            new SwingWorker<String, Void>() {
                @Override
                protected String doInBackground() throws Exception {
                    // Gọi phương thức downloadFile mới
                    return clientManager.downloadFile(fileId, fileToSave);
                }

                @Override
                protected void done() {
                    btnDownload.setEnabled(true); // Bật lại nút trên EDT
                    try {
                        String downloadResult = get();

                        if ("DOWNLOAD_SUCCESS".equals(downloadResult)) {
                            JOptionPane.showMessageDialog(frmMainClient.this, "Tải file thành công! Đã lưu tại: " + fileToSave.getAbsolutePath());
                        } else {
                            // Xử lý các lỗi phản hồi từ Server (FILE_NOT_FOUND, PERMISSION_DENIED, DOWNLOAD_FAIL)
                            JOptionPane.showMessageDialog(frmMainClient.this, "Tải file thất bại: " + downloadResult, "Lỗi", JOptionPane.ERROR_MESSAGE);
                        }
                    } catch (Exception ex) {
                        logger.log(Level.SEVERE, "Lỗi khi Download file", ex);
                        JOptionPane.showMessageDialog(frmMainClient.this, "Lỗi hệ thống khi download: " + ex.getMessage(), "Lỗi", JOptionPane.ERROR_MESSAGE);
                    }
                }
            }.execute();
        }
    }

    /**
     * Xử lý Xóa file (Delete)
     */
    private void handleDelete() {
        int selectedRow = fileTable.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn một file để xóa.", "Cảnh báo", JOptionPane.WARNING_MESSAGE);
            return;
        }

        // Lấy thông tin file trên EDT
        String fileIdStr = (String) tableModel.getValueAt(selectedRow, 0);
        int fileId = Integer.parseInt(fileIdStr);
        String fileName = (String) tableModel.getValueAt(selectedRow, 1);
        String status = (String) tableModel.getValueAt(selectedRow, 4);

        // Chỉ cho phép xóa file mình sở hữu
        if (status.equals("Shared")) {
            JOptionPane.showMessageDialog(this, "Bạn không thể xóa file được chia sẻ cho bạn.", "Lỗi", JOptionPane.ERROR_MESSAGE);
            return;
        }

        int confirm = JOptionPane.showConfirmDialog(this,
                "Bạn có chắc chắn muốn xóa file '" + fileName + "'?",
                "Xác nhận Xóa", JOptionPane.YES_NO_OPTION);

        if (confirm == JOptionPane.YES_OPTION) {
            btnDelete.setEnabled(false); // Vô hiệu hóa nút trên EDT

            new SwingWorker<String, Void>() {
                @Override
                protected String doInBackground() throws Exception {
                    // Gọi phương thức deleteFile
                    return clientManager.deleteFile(fileId);
                }

                @Override
                protected void done() {
                    try {
                        String deleteResult = get();

                        if ("DELETE_SUCCESS".equals(deleteResult)) {
                            JOptionPane.showMessageDialog(frmMainClient.this, "Đã xóa file '" + fileName + "' thành công!");
                            loadFileList(); // Cập nhật bảng
                        } else {
                            JOptionPane.showMessageDialog(frmMainClient.this, "Xóa file thất bại: " + deleteResult, "Lỗi", JOptionPane.ERROR_MESSAGE);
                        }
                    } catch (Exception ex) {
                        logger.log(Level.SEVERE, "Lỗi khi Xóa file", ex);
                        JOptionPane.showMessageDialog(frmMainClient.this, "Lỗi hệ thống khi xóa: " + ex.getMessage(), "Lỗi", JOptionPane.ERROR_MESSAGE);
                    } finally {
                        btnDelete.setEnabled(true); // Bật lại nút
                    }
                }
            }.execute();
        }
    }

    /**
     * Xử lý Chia sẻ file (Share)
     */
    private void handleShare() {
        int selectedRow = fileTable.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn một file để chia sẻ.", "Cảnh báo", JOptionPane.WARNING_MESSAGE);
            return;
        }

        // Lấy thông tin file trên EDT
        String fileIdStr = (String) tableModel.getValueAt(selectedRow, 0);
        int fileId = Integer.parseInt(fileIdStr);
        String fileName = (String) tableModel.getValueAt(selectedRow, 1);
        String status = (String) tableModel.getValueAt(selectedRow, 4);

        // Chỉ cho phép thao tác với file mình sở hữu (Status là "Owned")
        if (status.equals("Shared")) {
            JOptionPane.showMessageDialog(this, "Bạn chỉ có thể quản lý việc chia sẻ cho file bạn sở hữu ('Owned').", "Lỗi", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // 1. Ẩn form chính (tùy chọn) và vô hiệu hóa các nút
        this.setEnabled(false);

        // 2. Mở form frmShareFile và truyền thông tin cần thiết
        // SỬA DỤNG CONSTRUCTOR MỚI VÀ TRUYỀN 'this' VÀO ĐẦU TIÊN
        frmShareFile shareForm = new frmShareFile(this, fileId, fileName, clientManager);
        shareForm.setVisible(true);

        // Sau khi form frmShareFile đóng, hàm callback (hoặc dispose) sẽ được gọi, 
        // lúc đó ta có thể gọi loadFileList() để cập nhật lại bảng.
    }

    /**
     * Chuyển đổi kích thước byte sang định dạng MB, KB, GB
     */
    private String formatSize(long bytes) {
        if (bytes < 1024) {
            return bytes + " Bytes";
        }
        int unit = 1024;
        int exp = (int) (Math.log(bytes) / Math.log(unit));
        String pre = ("KMGTPE").charAt(exp - 1) + "B";
        return String.format("%.2f %s", bytes / Math.pow(unit, exp), pre);
    }

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        handleLogout();
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void btnUploadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUploadActionPerformed
        handleUpload();
    }//GEN-LAST:event_btnUploadActionPerformed

    private void btnDownloadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDownloadActionPerformed
        handleDownload();
    }//GEN-LAST:event_btnDownloadActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        handleDelete();
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnShareActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShareActionPerformed
        handleShare();
    }//GEN-LAST:event_btnShareActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnDownload;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnShare;
    private javax.swing.JButton btnUpload;
    private javax.swing.JTable fileTable;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblWelcome;
    // End of variables declaration//GEN-END:variables
}
