/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package filestorageclient;

import javax.swing.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.SwingWorker;

public class frmRegister extends javax.swing.JFrame {

    // Đối tượng quản lý kết nối Socket
    private final ClientSocketManager clientManager;
    // Form cha (để hiển thị lại khi cần)
    private final JFrame parentForm;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(frmRegister.class.getName());

    /**
     * Creates new form frmRegister
     */
    public frmRegister(JFrame parentForm, ClientSocketManager manager) {
        // Gán giá trị từ tham số truyền vào
        this.parentForm = parentForm;
        this.clientManager = manager;

        initComponents();

        this.setLocationRelativeTo(null);
        // Thiết lập hành vi khi đóng cửa sổ: Chỉ đóng form hiện tại, không thoát ứng dụng
        this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextField();
        txtPassword = new javax.swing.JPasswordField();
        txtConfirmPassword = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();
        btnRegister = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Đăng ký Tài khoản Mới");

        jLabel1.setText("Username:");

        jLabel2.setText("Password");

        txtUsername.setText("Username");

        txtPassword.setText("jPasswordField1");

        txtConfirmPassword.setText("jPasswordField1");

        jLabel3.setText("ConfirmPassword");

        btnRegister.setText("Register");
        btnRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegisterActionPerformed(evt);
            }
        });

        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        jLabel4.setText("Email");

        txtEmail.setText("Email");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addComponent(btnRegister)
                        .addGap(24, 24, 24)
                        .addComponent(btnCancel))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtPassword, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtUsername, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(24, 24, 24)
                                .addComponent(txtConfirmPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(103, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtConfirmPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRegister)
                    .addComponent(btnCancel))
                .addContainerGap(108, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Logic xử lý chức năng Đăng ký. Thực hiện kiểm tra dữ liệu đầu vào và gửi
     * yêu cầu Đăng ký đến Server qua SwingWorker.
     */
    private void handleRegister() {
        String username = txtUsername.getText().trim();
        String password = new String(txtPassword.getPassword());
        String confirmPassword = new String(txtConfirmPassword.getPassword());
        String email = txtEmail.getText().trim();

        // 1. Kiểm tra dữ liệu đầu vào (Validation)
        if (username.isEmpty() || password.isEmpty() || confirmPassword.isEmpty() || email.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập đầy đủ thông tin.", "Lỗi", JOptionPane.WARNING_MESSAGE);
            return;
        }

        if (!password.equals(confirmPassword)) {
            JOptionPane.showMessageDialog(this, "Mật khẩu xác nhận không khớp.", "Lỗi Mật khẩu", JOptionPane.ERROR_MESSAGE);
            txtPassword.setText("");
            txtConfirmPassword.setText("");
            return;
        }

        if (!email.contains("@") || email.length() < 5) {
            JOptionPane.showMessageDialog(this, "Email không hợp lệ.", "Lỗi Email", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // 2. Chuyển sang SwingWorker để Đăng ký
        btnRegister.setEnabled(false); // Vô hiệu hóa nút trên EDT

        new SwingWorker<String, Void>() {
            @Override
            protected String doInBackground() throws Exception {
                // Thao tác mạng chỉ chạy ở luồng nền 
                return clientManager.register(username, password, email);
            }

            @Override
            protected void done() {
                try {
                    // Xử lý phản hồi trên EDT
                    String result = get();

                    // 🔥 PHÂN TÍCH CÁC MÃ LỖI CHI TIẾT TỪ SERVER
                    switch (result) {
                        case "REGISTER_SUCCESS":
                            JOptionPane.showMessageDialog(frmRegister.this, "Đăng ký thành công! Bạn có thể đăng nhập ngay.", "Thành công", JOptionPane.INFORMATION_MESSAGE);
                            // Tự động chuyển về form Login
                            parentForm.setVisible(true);
                            frmRegister.this.dispose();
                            break;

                        case "REGISTER_FAIL_USERNAME_EXIST":
                            JOptionPane.showMessageDialog(frmRegister.this, "Tên đăng nhập này đã có người sử dụng. Vui lòng chọn tên khác.", "Lỗi Đăng ký", JOptionPane.ERROR_MESSAGE);
                            txtUsername.requestFocus();
                            break;

                        case "REGISTER_FAIL_EMAIL_EXIST":
                            JOptionPane.showMessageDialog(frmRegister.this, "Địa chỉ Email này đã được sử dụng. Vui lòng sử dụng Email khác.", "Lỗi Đăng ký", JOptionPane.ERROR_MESSAGE);
                            txtEmail.requestFocus();
                            break;

                        case "REGISTER_FAIL_DB_ERROR":
                            JOptionPane.showMessageDialog(frmRegister.this, "Đăng ký thất bại do lỗi CSDL nội bộ. Vui lòng thử lại sau.", "Lỗi Hệ thống", JOptionPane.ERROR_MESSAGE);
                            break;

                        case "ERROR_CONNECTION":
                            JOptionPane.showMessageDialog(frmRegister.this, "Lỗi kết nối Server. Vui lòng kiểm tra lại kết nối mạng.", "Lỗi Mạng", JOptionPane.ERROR_MESSAGE);
                            clientManager.connect(); // Thử kết nối lại
                            break;

                        case "ERROR_IO":
                            JOptionPane.showMessageDialog(frmRegister.this, "Lỗi giao tiếp với Server. Vui lòng thử lại.", "Lỗi I/O", JOptionPane.ERROR_MESSAGE);
                            break;

                        default:
                            // Bắt lỗi chung hoặc mã lỗi không xác định
                            JOptionPane.showMessageDialog(frmRegister.this, "Đăng ký thất bại. Lỗi không xác định: " + result, "Lỗi", JOptionPane.ERROR_MESSAGE);
                            break;
                    }
                } catch (Exception ex) {
                    logger.log(java.util.logging.Level.SEVERE, "Lỗi SwingWorker khi Đăng ký", ex);
                    JOptionPane.showMessageDialog(frmRegister.this, "Lỗi không xác định: " + ex.getMessage(), "Lỗi", JOptionPane.ERROR_MESSAGE);
                } finally {
                    btnRegister.setEnabled(true); // Bật lại nút trong finally
                }
            }
        }.execute(); // Chạy SwingWorker
    }
    private void btnRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisterActionPerformed
        handleRegister();
    }//GEN-LAST:event_btnRegisterActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        this.parentForm.setVisible(true); // Hiển thị lại form Login
        this.dispose();                   // Đóng form Đăng ký hiện tại
    }//GEN-LAST:event_btnCancelActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnRegister;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPasswordField txtConfirmPassword;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}
